# Generated by Django 3.2.23 on 2024-03-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('register_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('natal_sex', models.IntegerField(choices=[(0, 'Intersex'), (1, 'Female'), (2, 'Male')], default=0)),
                ('choosen_sex', models.IntegerField(choices=[(0, 'Cis'), (1, 'MTF'), (2, 'FTM'), (3, 'NB')], default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-register_date'],
            },
        ),
    ]
