# Generated by Django 3.2.23 on 2024-03-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_rename_parent_child_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='choosen_sex',
            new_name='choosen_sex_id',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='natal_sex',
            new_name='natal_sex_id',
        ),
    ]
