# Generated by Django 3.2.23 on 2024-03-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20240318_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='choosen_sex_id',
            new_name='choosen_sex',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='natal_sex_id',
            new_name='natal_sex',
        ),
    ]
